resources:
  - name: buildJfrogCliPluginGit
    type: GitRepo
    configuration:
      path: RobiNino/plugins-template-dev #todo
      gitProvider: robi_github #todo
      buildOn:
        # Manually trigger only
        commit: false
      branches:
        # Only build on the master
        include: master
      files:
        include: ^plugins\/.+

pipelines:
  - name: build_jfrog_cli_plugin_robi_dev
    steps:
      - name: BuildAndPush
        type: Bash
        configuration:
          integrations:
            - name: robi_eco_token
          inputResources:
            - name: buildJfrogCliPluginGit
          runtime:
            type: image
            image:
              auto:
                language: go
                versions:
                  - "1.14.4"
          environmentVariables:
            # CONSTS:
            CI: "true"
            JFROG_CLI_PLUGINS_REGISTRY_URL: "https://ecosysjfrog.jfrog.io/artifactory" # todo
            JFROG_CLI_PLUGINS_RT_REGISTRY_REPO: "jfrog-cli-plugins"
            # CUSTOM:
            JFROG_CLI_PLUGIN_DESCRIPTOR_FILE_NAME: "build-report.yml" # todo
            # REMOVE:
            JFROG_CLI_PLUGIN_PLUGIN_NAME: "plugin-name"
            JFROG_CLI_PLUGIN_DOMAIN_NAME: "jfrog"
            JFROG_CLI_PLUGIN_REPO_NAME: "jfrog-cli-plugins"
            JFROG_CLI_PLUGIN_RELATIVE_PATH: "blank-if-in-root"
            JFROG_CLI_PLUGIN_VERSION: "v1.0.0"
        execution:
          onStart:
            - update_commit_status buildJfrogCliPluginGit --context "$step_name"
          onExecute:
            # Install yq to parse yaml.
            - GO111MODULE=on go get github.com/mikefarah/yq/v3
            # Get params from yaml.
            - ymlPath="$res_buildJfrogCliPluginGit_resourcePath/plugins/$JFROG_CLI_PLUGIN_DESCRIPTOR_FILE_NAME"
            - echo $ymlPath # todo remove
            - ll "$res_buildJfrogCliPluginGit_resourcePath/"
            - yq r $ymlPath
          #       # Clone plugin repo.
          #       - git clone https://github.com/$JFROG_CLI_PLUGIN_DOMAIN_NAME/$JFROG_CLI_PLUGIN_REPO_NAME
          #       # Copy the plugin release script from registry repo to plugin repo.
          #       - cp "$res_buildJfrogCliPluginGit_resourcePath/pipelinesScripts/pluginRelease.sh" "./$JFROG_CLI_PLUGIN_REPO_NAME/$JFROG_CLI_PLUGIN_RELATIVE_PATH"
          #       - pushd $JFROG_CLI_PLUGIN_REPO_NAME/$JFROG_CLI_PLUGIN_RELATIVE_PATH
          #       - bash "./pluginRelease.sh"
          #       - popd
          onComplete:
            - update_commit_status buildJfrogCliPluginGit --context "$step_name"