resources:
  - name: buildJfrogCliPluginGit
    type: GitRepo
    configuration:
      path: RobiNino/plugins-template-dev #todo
      gitProvider: robi_github #todo
      buildOn:
        # Build on commit and tags
        tagCreate: true
      branches:
        # Only build on the master
        include: master
      files:
        include: ^plugins\/.+

pipelines:
  - name: build_jfrog_cli_plugin
    steps:
      - name: BuildAndPush
        type: Bash
        configuration:
          integrations:
            - name: releases_jfrog
          inputResources:
            - name: buildJfrogCliPluginGit
          runtime:
            type: image
            image:
              auto:
                language: go
                versions:
                  - "1.14.4"
          environmentVariables:
            CI: "true"
            JFROG_CLI_PLUGINS_REGISTRY_URL: "https://releases.jfrog.io/artifactory"
            # Repo name in artifactory
            JFROG_CLI_PLUGINS_REGISTRY_REPO: "jfrog-cli-plugins"
            JFROG_CLI_PLUGIN_PLUGIN_NAME: "build-report"
            JFROG_CLI_PLUGIN_DOMAIN_NAME: "jfrog"
            JFROG_CLI_PLUGIN_REPO_NAME: "jfrog-cli-plugins"
            JFROG_CLI_PLUGIN_RELATIVE_PATH: "build-report"
            JFROG_CLI_PLUGIN_VERSION: "v1.0.0"
        execution:
          onStart:
            - update_commit_status buildJfrogCliPluginGit --context "$step_name"
          onExecute:
            # Clone plugin repo.
            - git clone https://github.com/$JFROG_CLI_PLUGIN_DOMAIN_NAME/$JFROG_CLI_PLUGIN_REPO_NAME
            # Copy the plugin release script from registry repo to plugin repo.
            - cp "$res_buildJfrogCliPluginGit_resourcePath/pipelinesScripts/pluginRelease.sh" "./$JFROG_CLI_PLUGIN_REPO_NAME/$JFROG_CLI_PLUGIN_RELATIVE_PATH"
            - pushd $JFROG_CLI_PLUGIN_REPO_NAME/$JFROG_CLI_PLUGIN_RELATIVE_PATH
            - sh "./pluginRelease.sh"
            - popd
          onComplete:
            - update_commit_status buildJfrogCliPluginGit --context "$step_name"