resources:
  - name: buildJfrogCliPluginGit
    type: GitRepo
    configuration:
      path: RobiNino/plugins-template-dev #todo
      gitProvider: robi_github #todo
      buildOn:
        # Manually trigger only
        commit: false
      branches:
        # Only build on the master
        include: master
      files:
        include: ^plugins\/.+

pipelines:
  - name: build_jfrog_cli_plugin_robi_dev
    steps:
      - name: BuildAndPush
        type: Bash
        configuration:
          integrations:
            - name: robi_eco_token
          inputResources:
            - name: buildJfrogCliPluginGit
          runtime:
            type: image
            image:
              auto:
                language: go
                versions:
                  - "1.14.4"
          environmentVariables:
            JFROG_CLI_PLUGIN_DESCRIPTOR_FILE_NAME: "build-report.yml" # todo
        execution:
          onStart:
            - update_commit_status buildJfrogCliPluginGit --context "$step_name"
          onExecute:
            # Install yq to parse yaml.
            - GO111MODULE=on go get github.com/mikefarah/yq/v3
            # Extract params from yaml.
            - ymlPath="$res_buildJfrogCliPluginGit_resourcePath/plugins/$JFROG_CLI_PLUGIN_DESCRIPTOR_FILE_NAME"
            - echo "extracting details from $ymlPath"
            - JFROG_CLI_PLUGIN_PLUGIN_NAME=$(yq r $ymlPath "pluginName") && echo $JFROG_CLI_PLUGIN_PLUGIN_NAME
            - JFROG_CLI_PLUGIN_VERSION=$(yq r $ymlPath "version") && echo $JFROG_CLI_PLUGIN_VERSION
            - pluginRepoFullUrl=$(yq r $ymlPath "repository") && echo $pluginRepoFullUrl
            - pluginRepoName=$(basename $pluginRepoFullUrl .git) && echo $pluginRepoName
            - pluginRelativePath=$(yq r $ymlPath "relativePath") && echo $pluginRelativePath
            # Export vars needed in the release script.
            - export CI="true"
            - export JFROG_CLI_PLUGINS_REGISTRY_URL="https://ecosysjfrog.jfrog.io/artifactory" #todo
            - export JFROG_CLI_PLUGINS_RT_REGISTRY_REPO="jfrog-cli-plugins"
            - export JFROG_CLI_PLUGIN_VERSION
            - export JFROG_CLI_PLUGIN_PLUGIN_NAME
            # Clone plugin repo.
            - git clone $pluginRepoFullUrl
            # Copy the plugin release script from registry repo to plugin repo.
            - cp "$res_buildJfrogCliPluginGit_resourcePath/pipelinesScripts/pluginRelease.sh" "./$pluginRepoName/$pluginRelativePath"
            - pushd "./$pluginRepoName/$pluginRelativePath"
            - bash "./pluginRelease.sh"
            - popd
          onComplete:
            - update_commit_status buildJfrogCliPluginGit --context "$step_name"