resources:
  - name: buildJfrogCliPluginGit
    type: GitRepo
    configuration:
      path: RobiNino/plugins-template-dev #todo
      gitProvider: robi_github #todo
      buildOn:
        # Build on commit and tags
        tagCreate: true
      branches:
        # Only build on the master
        include: master

pipelines:
  - name: build_jfrog_cli_plugin
    steps:
      - name: BuildAndPush
        type: Bash
        configuration:
          integrations:
            - name: robi_eco #todo releases_jfrog
          inputResources:
            - name: buildJfrogCliPluginGit
          runtime:
            type: image
            image:
              auto:
                language: go
                versions:
                  - "1.14.4"
          environmentVariables:
            JFROG_CLI_OFFER_CONFIG: "false"
            JFROG_CLI_PLUGIN_PLUGIN_NAME: "plugin-test"
            JFROG_CLI_PLUGIN_DOMAIN_NAME: "RobiNino"
            JFROG_CLI_PLUGIN_REPO_NAME: "plugins-template-dev"
            JFROG_CLI_PLUGIN_VERSION: "v1.0.4"
            JFROG_CLI_PLUGINS_REGISTRY_URL: "https://ecosysjfrog.jfrog.io/artifactory"
            JFROG_CLI_PLUGINS_REGISTRY_REPO: "jfrog-cli-plugins"
        execution:
          onStart:
            - update_commit_status buildJfrogCliPluginGit --context "$step_name"
          onExecute:
            - git clone https://github.com/$JFROG_CLI_PLUGIN_DOMAIN_NAME/$JFROG_CLI_PLUGIN_REPO_NAME
            - pushd $JFROG_CLI_PLUGIN_REPO_NAME
            - sh "pipelinesScripts/pluginRelease.sh"
            - popd
          onComplete:
            - update_commit_status buildJfrogCliPluginGit --context "$step_name"